# JOB_NAME=$1
# WORKSPACE=$2
# VERSION_NUMBER=$3
# PLATEFORME_SOURCE=$4
# VERSION_NAME="V$3"
# PLATEFORME=`echo $JOB_NAME |cut -d"_" -f1`

# echo $JOB_NAME
# echo $WORKSPACE
# echo $VERSION_NUMBER

echo $1
